import { DataInteractive } from '../src/models/simple.models'
const dataShops2: DataInteractive[] = [
  {
    id: '0',
    idmap: 'SvgjsRect1009',
    title: 'Bruen - Kessler',
    slug: 'https://soulful-racism.info',
    description: 'Focused bi-directional middleware',
    image: 'https://loremflickr.com/128/128/abstract?73275',
  },
  {
    id: '1',
    idmap: 'SvgjsRect1010',
    title: 'Reynolds, Orn and Fadel',
    slug: 'https://incomparable-bunghole.moscow',
    description: 'Networked transitional portal',
    image: 'https://loremflickr.com/128/128/abstract?36278',
  },
  {
    id: '2',
    idmap: 'SvgjsRect1011',
    title: 'Murazik, Renner and Funk',
    slug: 'https://webbed-list.рф',
    description: 'Implemented background interface',
    image: 'https://loremflickr.com/128/128/abstract?44043',
  },
  {
    id: '3',
    idmap: 'SvgjsRect1012',
    title: 'Hilpert - Ernser',
    slug: 'https://cooperative-obi.info',
    description: 'Universal responsive superstructure',
    image: 'https://loremflickr.com/128/128/abstract?11672',
  },
  {
    id: '4',
    idmap: 'SvgjsRect1013',
    title: 'Ortiz Торг',
    slug: 'https://round-hire.rus',
    description: 'User-friendly fault-tolerant architecture',
    image: 'https://loremflickr.com/128/128/abstract?58180',
  },
  {
    id: '5',
    idmap: 'SvgjsRect1014',
    title: 'Williamson - Wolf',
    slug: 'http://unused-lecture.su',
    description: 'Business-focused optimizing implementation',
    image: 'https://loremflickr.com/128/128/abstract?77894',
  },
  {
    id: '6',
    idmap: 's-K0_4',
    title: 'Kling, Glover and Paucek',
    slug: 'https://beloved-strawman.edo',
    description: 'Expanded foreground system engine',
    image: 'https://loremflickr.com/128/128/abstract?73762',
  },
  {
    id: '7',
    idmap: 'SvgjsRect1016',
    title: 'Zboncak, Schiller and Collier',
    slug: 'http://conscious-dishwasher.москва',
    description: 'Fundamental local architecture',
    image: 'https://loremflickr.com/128/128/abstract?86477',
  },
  {
    id: '8',
    idmap: 's-K0_5',
    title: 'Zulauf Пром',
    slug: 'https://witty-retouching.pro',
    description: 'Future-proofed 24/7 methodology',
    image: 'https://loremflickr.com/128/128/abstract?22380',
  },
  {
    id: '9',
    idmap: 's-037',
    title: 'Becker - Schmitt',
    slug: 'https://known-psychologist.store',
    description: 'Re-contextualized fault-tolerant internet solution',
    image: 'https://loremflickr.com/128/128/abstract?48835',
  },
  {
    id: '10',
    idmap: 's-033',
    title: 'Collier - Osinski',
    slug: 'http://informal-specialist.host',
    description: 'Organized composite throughput',
    image: 'https://loremflickr.com/128/128/abstract?42900',
  },
  {
    id: '11',
    idmap: 's-030',
    title: 'Bauch, Ziemann and Hickle',
    slug: 'http://gleeful-conversation.com',
    description: 'Balanced leading edge leverage',
    image: 'https://loremflickr.com/128/128/abstract?28934',
  },
  {
    id: '12',
    idmap: 's-031',
    title: 'Goodwin, Mann and Halvorson',
    slug: 'https://dizzy-stepson.su',
    description: 'Fundamental leading edge interface',
    image: 'https://loremflickr.com/128/128/abstract?71569',
  },
  {
    id: '13',
    idmap: 's-027',
    title: 'Runte Снаб',
    slug: 'http://indelible-aglet.ru',
    description: 'Progressive mission-critical definition',
    image: 'https://loremflickr.com/128/128/abstract?71523',
  },
  {
    id: '14',
    idmap: 's-028',
    title: 'Hoppe, Larson and Prosacco',
    slug: 'http://profuse-estimate.biz',
    description: 'Managed directional methodology',
    image: 'https://loremflickr.com/128/128/abstract?82727',
  },
  {
    id: '15',
    idmap: 's-010',
    title: 'Fisher - Satterfield',
    slug: 'http://teeming-shore.онлайн',
    description: 'Up-sized methodical migration',
    image: 'https://loremflickr.com/128/128/abstract?7445',
  },
  {
    id: '16',
    idmap: 's-025',
    title: 'Hackett, Grady and Mertz',
    slug: 'http://ornery-credit.net',
    description: 'Polarised explicit strategy',
    image: 'https://loremflickr.com/128/128/abstract?37954',
  },
  {
    id: '17',
    idmap: 's-026',
    title: 'Goyette, Hansen and Murphy',
    slug: 'https://tired-step-aunt.сайт',
    description: 'Exclusive discrete software',
    image: 'https://loremflickr.com/128/128/abstract?43985',
  },
  {
    id: '18',
    idmap: 's-033_1',
    title: 'Franecki, Stehr and Pacocha',
    slug: 'https://queasy-exocrine.su',
    description: 'Proactive mobile access',
    image: 'https://loremflickr.com/128/128/abstract?35727',
  },
  {
    id: '19',
    idmap: 's-045',
    title: 'Hackett, Hamill and Rosenbaum',
    slug: 'https://unfit-pub.tech',
    description: 'Persevering didactic database',
    image: 'https://loremflickr.com/128/128/abstract?24319',
  },
  {
    id: '20',
    idmap: 's-017',
    title: 'Marks, Nienow and Hagenes',
    slug: 'https://wicked-estrogen.moscow',
    description: 'Compatible transitional artificial intelligence',
    image: 'https://loremflickr.com/128/128/abstract?8479',
  },
  {
    id: '21',
    idmap: 's-019',
    title: 'Goyette - Feil',
    slug: 'http://infantile-unique.moscow',
    description: 'Ameliorated neutral functionalities',
    image: 'https://loremflickr.com/128/128/abstract?8015',
  },
  {
    id: '22',
    idmap: 's-023',
    title: 'Rippin - Schamberger',
    slug: 'http://alarming-frontier.москва',
    description: 'Mandatory system-worthy toolset',
    image: 'https://loremflickr.com/128/128/abstract?98603',
  },
  {
    id: '23',
    idmap: 's-024',
    title: 'Block - Herzog',
    slug: 'https://putrid-boutique.онлайн',
    description: 'Exclusive stable projection',
    image: 'https://loremflickr.com/128/128/abstract?47170',
  },
  {
    id: '24',
    idmap: 's-021',
    title: 'Jacobi Трейд',
    slug: 'https://humongous-union.su',
    description: 'Sharable directional structure',
    image: 'https://loremflickr.com/128/128/abstract?89062',
  },
  {
    id: '25',
    idmap: 's-020',
    title: "O'Hara, Torphy and Bashirian",
    slug: 'https://bumpy-wallet.org',
    description: 'Sharable bandwidth-monitored portal',
    image: 'https://loremflickr.com/128/128/abstract?31897',
  },
  {
    id: '26',
    idmap: 's-022',
    title: 'Hansen - Rempel',
    slug: 'https://knotty-newspaper.su',
    description: 'Assimilated content-based budgetary management',
    image: 'https://loremflickr.com/128/128/abstract?61412',
  },
  {
    id: '27',
    idmap: 's-022_1',
    title: 'Ryan Системс',
    slug: 'http://long-inhibition.host',
    description: 'Synergized fault-tolerant installation',
    image: 'https://loremflickr.com/128/128/abstract?1514',
  },
  {
    id: '28',
    idmap: 's-015',
    title: 'Konopelski, Keebler and Predovic',
    slug: 'http://broken-crewman.edo',
    description: 'Intuitive non-volatile implementation',
    image: 'https://loremflickr.com/128/128/abstract?63824',
  },
  {
    id: '29',
    idmap: 's-016_2',
    title: 'Orn Инкорпорэйтед',
    slug: 'https://tattered-settler.info',
    description: 'Assimilated asynchronous algorithm',
    image: 'https://loremflickr.com/128/128/abstract?29213',
  },
  {
    id: '30',
    idmap: 's-016',
    title: 'Wiza, Doyle and Roob',
    slug: 'https://sociable-tom-tom.moscow',
    description: 'Customizable interactive model',
    image: 'https://loremflickr.com/128/128/abstract?31463',
  },
  {
    id: '31',
    idmap: 's-016_1',
    title: 'Quigley - Cartwright',
    slug: 'http://overcooked-coyote.net',
    description: 'Extended demand-driven collaboration',
    image: 'https://loremflickr.com/128/128/abstract?9426',
  },
  {
    id: '32',
    idmap: 's-040',
    title: 'Connelly Групп',
    slug: 'https://probable-imitation.рф',
    description: 'Ameliorated bandwidth-monitored capacity',
    image: 'https://loremflickr.com/128/128/abstract?18529',
  },
  {
    id: '33',
    idmap: 's-039',
    title: 'Rempel - Balistreri',
    slug: 'https://educated-blind.host',
    description: 'De-engineered interactive productivity',
    image: 'https://loremflickr.com/128/128/abstract?4454',
  },
  {
    id: '34',
    idmap: 's-038',
    title: 'Emard Системс',
    slug: 'http://cooked-number.рф',
    description: 'Persevering neutral benchmark',
    image: 'https://loremflickr.com/128/128/abstract?4149',
  },
  {
    id: '35',
    idmap: 's-042',
    title: 'Parker Лимитед',
    slug: 'https://uncommon-grouse.ru',
    description: 'Self-enabling 4th generation ability',
    image: 'https://loremflickr.com/128/128/abstract?94021',
  },
  {
    id: '36',
    idmap: 's-043',
    title: 'Wolff',
    slug: 'http://odd-calm.pro',

    image: 'https://loremflickr.com/128/128/abstract?52941',
  },
  {
    id: '37',
    idmap: 's-041',
    title: 'Hauck Инкорпорэйтед Системс Трейд',
    slug: 'https://grateful-cabin.online',
    description:
      'Polarised needs-based initiative. <strong> Системс Трейд firmware is licensed under the GPL. </strong>Системс Трейд firmware is licensed under the GPL.  But writing all the JSON parsing code by hand becomes time-consuming and error-prone if we have a lot of model classes. Luckily, we can use code generation tools such as json_serializable and Freezed to automate the process.',
    image: 'https://loremflickr.com/128/128/abstract?43320',
  },
  {
    id: '38',
    idmap: 's-018',
    title: 'Nitzsche Сбыт',
    slug: 'http://strong-barracks.store',
    description: 'Synchronised coherent parallelism',
    image: 'https://loremflickr.com/128/128/abstract?27855',
  },
  {
    id: '39',
    idmap: 's-029',
    title: 'Metz Рус',
    slug: 'https://sturdy-typhoon.club',
    description: 'Mandatory context-sensitive moratorium',
    image: 'https://loremflickr.com/128/128/abstract?57365',
  },
  {
    id: '40',
    idmap: 's-035',
    title: 'Feil Сбыт',
    slug: 'http://ornery-approach.rus',
    description: 'Customer-focused disintermediate neural-net',
    image: 'https://loremflickr.com/128/128/abstract?64942',
  },
  {
    id: '41',
    idmap: 's-013',
    title: 'Boehm Инкорпорэйтед',
    slug: 'http://tepid-television.москва',
    description: 'Synergistic multi-state open system',
    image: 'https://loremflickr.com/128/128/abstract?14055',
  },
  {
    id: '42',
    idmap: 's-K0_151',
    title: 'Kris Инкорпорэйтед',
    slug: 'https://separate-calorie.edo',
    description: 'Down-sized cohesive archive',
    image: 'https://loremflickr.com/128/128/abstract?19312',
  },
  {
    id: '43',
    idmap: 's-K0_5XXXX',
    title: 'Kertzmann Лимитед',
    slug: 'https://regal-rage.edo',
    description: 'Switchable 6th generation focus group',
    image: 'https://loremflickr.com/128/128/abstract?35265',
  },
  {
    id: '44',
    idmap: 's-048',
    title: 'Альфа-банк',
    slug: 'https://alfabank.ru',
    description: 'The most phygital bank. Сочетаем цифровой и физический опыт',
    image: 'https://loremflickr.com/128/128/abstract?89292',
  },
  {
    id: '45',
    idmap: 's-049',
    title: "Bailey - O'Connell",
    slug: 'https://circular-obligation.host',
    description: 'Re-contextualized encompassing throughput',
    image: 'https://loremflickr.com/128/128/abstract?89035',
  },
  {
    id: '46',
    idmap: 's-052',
    title: 'Райффайзен Банк',
    slug: 'http://adorable-reef.москва',
    description: 'Up-sized global pricing structure',
    image: 'https://loremflickr.com/128/128/abstract?76365',
  },
  {
    id: '47',
    idmap: 's-K0_3',
    title: 'Walter Торг',
    slug: 'https://careful-pantology.ru',
    description: 'Future-proofed solution-oriented core',
    image: 'https://loremflickr.com/128/128/abstract?98819',
  },
  {
    id: '48',
    idmap: 's-044',
    title: 'Simonis Пром',
    slug: 'https://key-explorer.moscow',
    description: 'Triple-buffered system-worthy encryption',
    image: 'https://loremflickr.com/128/128/abstract?35687',
  },
]
const dataShops3: DataInteractive[] = [
  {
    id: '0',
    idmap: 'item-terrasa',
    title: 'Терраса',
    slug: '/terrasa',
    description: 'Терраса паред домом. 28,31 м2',
    image: 'https://loremflickr.com/128/128/abstract?8225',
  },
  {
    id: '1',
    idmap: 'item-wc-1',
    title: 'Туалет.',
    slug: '/wc',
    description: 'Площад помещения 3,61 м2',
    image: 'https://loremflickr.com/128/128/abstract?18629',
  },
  {
    id: '2',
    idmap: 'item-room-1',
    title: 'Гостинная + Кухня + Столовая.',
    slug: '/apartment',
    description: 'Площад помещения 48,24 м2',
    image: 'https://loremflickr.com/128/128/abstract?42696',
  },
  {
    id: '3',
    idmap: 'item-hall-1',
    title: 'Прихожая',
    slug: '/hall',
    description: 'Площад помещения 4,6 м2',
    image: 'https://loremflickr.com/128/128/abstract?70521',
  },
  {
    id: '4',
    idmap: 'item-hall-2',
    title: 'Прихожая',
    slug: '/hall',
    description: 'Площад помещения 4,6 м2',
    image: 'https://loremflickr.com/128/128/abstract?21376',
  },
  {
    id: '5',
    idmap: 'item-bathroom-1',
    title: 'Ванная',
    slug: '/bathroom',
    description: 'Площад помещения 6,82 м2',
    image: 'https://loremflickr.com/128/128/abstract?54426',
  },
  {
    id: '6',
    idmap: 'item-bathroom-2',
    title: 'Ванная',
    slug: '/bathroom',
    description: 'Площад помещения 6,82 м2',
    image: 'https://loremflickr.com/128/128/abstract?87579',
  },
  {
    id: '7',
    idmap: 'item-badroom-1',
    title: 'Спальня',
    slug: '/badroom',
    description: 'Площад помещения 13,78 м2',
    image: 'https://loremflickr.com/128/128/abstract?77889',
  },
  {
    id: '8',
    idmap: 'item-badroom-2',
    title: 'Спальня',
    slug: '/badroom',
    description: 'Площад помещения 13,78 м2',
    image: 'https://loremflickr.com/128/128/abstract?17556',
  },
  {
    id: '9',
    idmap: 'item-floor-2',
    title: 'Лестница',
    slug: '/upstire',
    description: 'Лестница на 2 этаж',
    image: 'https://loremflickr.com/128/128/abstract?38796',
  },
  {
    id: '10',
    idmap: 'item-enter-1',
    title: 'Вход',
    slug: '/enter',
    description: 'Вход на 1 этаж',
    image: 'https://loremflickr.com/128/128/abstract?72211',
  },
  {
    id: '11',
    idmap: 'item-enter-2',
    title: 'Вход',
    slug: '/enter',
    description: 'Вход на 1 этаж',
    image: 'https://loremflickr.com/128/128/abstract?29267',
  },
]

const dataShops: DataInteractive[] = [
  {
    id: '0',
    idmap: 'item-0',
    title: 'Cronin, Bayer and Halvorson',
    slug: 'http://brief-function.tech',
    description: 'Optimized 3rd generation paradigm',
    image: 'https://loremflickr.com/128/128/abstract?48284',
  },
  {
    id: '1',
    idmap: 'item-1',
    title: 'Bauch, Gutmann and Beahan',
    slug: 'http://odd-tomography.net',
    description: 'Team-oriented neutral groupware',
    image: 'https://loremflickr.com/128/128/abstract?28712',
  },
  {
    id: '2',
    idmap: 'item-2',
    title: 'Friesen, Barton and Thompson',
    slug: 'https://sweltering-iris.москва',
    description: 'Monitored grid-enabled budgetary management',
    image: 'https://loremflickr.com/128/128/abstract?91223',
  },
  {
    id: '3',
    idmap: 'item-3',
    title: 'Swaniawski - Yundt',
    slug: 'http://whimsical-boogeyman.tech',
    description: 'Polarised 4th generation circuit',
    image: 'https://loremflickr.com/128/128/abstract?16676',
  },
  {
    id: '4',
    idmap: 'item-4',
    title: 'Daniel Пром',
    slug: 'http://urban-warfare.online',
    description: 'Ergonomic motivating circuit',
    image: 'https://loremflickr.com/128/128/abstract?76011',
  },
  {
    id: '5',
    idmap: 'item-5',
    title: 'Jacobi, Barrows and Macejkovic',
    slug: 'http://constant-warlock.biz',
    description: 'Seamless composite pricing structure',
    image: 'https://loremflickr.com/128/128/abstract?30033',
  },
  {
    id: '6',
    idmap: 'item-6',
    title: 'Gleason - Kuhic',
    slug: 'http://female-kimono.biz',
    description: 'Integrated context-sensitive core',
    image: 'https://loremflickr.com/128/128/abstract?60450',
  },
  {
    id: '7',
    idmap: 'item-7',
    title: 'Pollich Системс',
    slug: 'https://irresponsible-bratwurst.ru',
    description: 'Monitored mission-critical intranet',
    image: 'https://loremflickr.com/128/128/abstract?94379',
  },
  {
    id: '8',
    idmap: 'item-8',
    title: 'Mayer, Dooley and Bayer',
    slug: 'https://chilly-formicarium.net',
    description: 'Robust upward-trending workforce',
    image: 'https://loremflickr.com/128/128/abstract?73910',
  },
  {
    id: '9',
    idmap: 'item-9',
    title: 'Kuphal - Olson',
    slug: 'https://tall-mask.org',
    description: 'Integrated well-modulated forecast',
    image: 'https://loremflickr.com/128/128/abstract?68843',
  },
  {
    id: '10',
    idmap: 'item-10',
    title: 'Gaylord, Ebert and Maggio',
    slug: 'http://half-speed.info',
    description: 'Adaptive directional encoding',
    image: 'https://loremflickr.com/128/128/abstract?60497',
  },
  {
    id: '11',
    idmap: 'item-11',
    title: 'Ondricka, Kertzmann and Flatley',
    slug: 'http://physical-ranch.online',
    description: 'Future-proofed incremental Graphical User Interface',
    image: 'https://loremflickr.com/128/128/abstract?26781',
  },
  {
    id: '12',
    idmap: 'item-12',
    title: 'Parker Рус',
    slug: 'http://crafty-pick.ru',
    description: 'Secured zero tolerance software',
    image: 'https://loremflickr.com/128/128/abstract?60272',
  },
  {
    id: '13',
    idmap: 'item-13',
    title: 'Auer - Douglas',
    slug: 'http://agreeable-tortoise.host',
    description: 'Mandatory solution-oriented capacity',
    image: 'https://loremflickr.com/128/128/abstract?28911',
  },
  {
    id: '14',
    idmap: 'item-14',
    title: 'Price, Hackett and Funk',
    slug: 'http://hasty-psychiatrist.space',
    description: 'Adaptive high-level hub',
    image: 'https://loremflickr.com/128/128/abstract?26373',
  },
  {
    id: '15',
    idmap: 'item-15',
    title: 'Rau, Barrows and Balistreri',
    slug: 'http://ruddy-pursuit.pro',
    description: 'Synergized asynchronous interface',
    image: 'https://loremflickr.com/128/128/abstract?39357',
  },
  {
    id: '16',
    idmap: 'item-16',
    title: 'Eva - студия красоты',
    slug: 'https://well-documented-bun.info',
    description: 'Balanced responsive model',
    image: 'https://loremflickr.com/128/128/abstract?10279',
  },
  {
    id: '17',
    idmap: 'item-17',
    title: 'Тамани - ресторан',
    slug: 'https://elderly-appearance.edo',
    description: 'Persistent tertiary artificial intelligence',
    image: 'https://loremflickr.com/128/128/abstract?52977',
  },
  {
    id: '18',
    idmap: 'item-18',
    title: 'Greenholt - Kunde',
    slug: 'https://noteworthy-deficit.space',
    description: 'Optional disintermediate data-warehouse',
    image: 'https://loremflickr.com/128/128/abstract?47765',
  },
  {
    id: '19',
    idmap: 'item-19',
    title: 'Stracke - Bartell',
    slug: 'https://kaleidoscopic-tournament.store',
    description: 'Profit-focused modular database',
    image: 'https://loremflickr.com/128/128/abstract?45877',
  },
  {
    id: '20',
    idmap: 'item-20',
    title: 'Dare - Senger',
    slug: 'http://overlooked-citrus.rus',
    description: 'Function-based interactive time-frame',
    image: 'https://loremflickr.com/128/128/abstract?84056',
  },
  {
    id: '21',
    idmap: 'item-21',
    title: 'Rolls-Royce',
    slug: 'http://sarcastic-buffalo.press',
    description: 'Focused mission-critical circuit',
    image: 'https://loremflickr.com/128/128/abstract?71820',
  },
  {
    id: '22',
    idmap: 'item-22',
    title: 'Nader, Bernier and Veum',
    slug: 'http://fresh-ethics.host',
    description: 'Quality-focused encompassing pricing structure',
    image: 'https://loremflickr.com/128/128/abstract?68716',
  },
  {
    id: '23',
    idmap: 'item-23',
    title: 'Pfeffer - Botsford',
    slug: 'https://expensive-gigantism.su',
    description: 'Programmable dynamic support',
    image: 'https://loremflickr.com/128/128/abstract?91104',
  },
  {
    id: '24',
    idmap: 'item-24',
    title: 'Christiansen, Greenholt and Lebsack',
    slug: 'http://powerful-patina.host',
    description: 'Horizontal multi-state utilisation',
    image: 'https://loremflickr.com/128/128/abstract?99182',
  },
  {
    id: '25',
    idmap: 'item-25',
    title: 'Hagenes Групп',
    slug: 'https://gullible-suggestion.rus',
    description: 'Grass-roots even-keeled complexity',
    image: 'https://loremflickr.com/128/128/abstract?14906',
  },
  {
    id: '26',
    idmap: 'item-26',
    title: 'Schowalter Торг',
    slug: 'http://disfigured-okra.su',
    description: 'Universal motivating portal',
    image: 'https://loremflickr.com/128/128/abstract?83047',
  },
  {
    id: '27',
    idmap: 'item-27',
    title: 'Goyette - Jacobi',
    slug: 'https://graceful-placode.club',
    description: 'Up-sized homogeneous projection',
    image: 'https://loremflickr.com/128/128/abstract?87495',
  },
  {
    id: '28',
    idmap: 'item-28',
    title: 'Prohaska Рус',
    slug: 'http://assured-messy.rus',
    description: 'Innovative real-time parallelism',
    image: 'https://loremflickr.com/128/128/abstract?57826',
  },
  {
    id: '29',
    idmap: 'item-29',
    title: 'Royal Wellness club',
    slug: 'http://warlike-cassava.ru',
    description: 'Automated regional solution',
    image: 'https://loremflickr.com/128/128/abstract?78670',
  },
  {
    id: '30',
    idmap: 'item-30',
    title: 'Tatler Club',
    slug: 'https://delicious-tan.edo',
    description: 'Quality-focused disintermediate hierarchy',
    image: 'https://loremflickr.com/128/128/abstract?2612',
  },
  {
    id: '31',
    idmap: 'item-31',
    title: 'Диорама',
    slug: 'https://gracious-spotlight.store',
    description: 'Assimilated background capacity',
    image: 'https://loremflickr.com/128/128/abstract?25853',
  },
  {
    id: '32',
    idmap: 'item-32',
    title: 'Considine, McClure and Pagac',
    slug: 'http://appropriate-occupation.moscow',
    description: 'Inverse leading edge website',
    image: 'https://loremflickr.com/128/128/abstract?34227',
  },
]
export { dataShops, dataShops2, dataShops3 }
